### ISSUE TITLE
HOME run does not end

### ISSUE THREAD

**Issue by nuriaserra** [ListerLab/HOME#20]
Hello,

I'm having problems to run HOME, because the runs never end. It finds the mitochondrial DMRs quite quickly, but after that it does not produce any other result. I have tried it with 48h and 32 processors for 2 samples of Arabidopsis, and it always crashes because it reaches the time limit.

The command I am using is:
HOME-pairwise -t CG -i ./sample_file_CG_comparison1.txt -o ./output_comparison1_CG -npp 32

With the last version of home (0.9).

Thank you for your help,

Núria

**Comment by nuriaserra** [comment]
Hello Akanksha,


In this case I do not have any replicates, although for another experiment I have.


It's running now, I will tell you the results 😊 thank you!


Best,


Núria

Nuria Serra
Intern

Gregor Mendel Institute of Molecular Plant Biology GmbH
Dr. Bohr-Gasse 3, 1030 Vienna, Austria
nuria.serra@gmi.oeaw.ac.at
http://www.gmi.oeaw.ac.at

[cid:gmisig_231_92997f80-ec0b-4736-9e1e-b20adcb9ca37.png]


________________________________

**Comment by Akanksha2511** [comment]
Hi Núria,

Its pretty surprising that run is taking so long. Even without **-sin** parameter, it should finish within 2 hours, roughly (more quickly for plant genome). So, Just a bit of detail, without -sin parameter, HOME runs parallel processes for each chromosome (5 in case of Arabidopsis). With -sin parameter it breaks the single chromosome into chunks (depending on npp parameter) and will run parallel for each chunk. If you don't use -sin parameter and run HOME in default mode, set the npp parameter to max. no. of chromosomes the data have or less if your system does not allow it. Setting it more than that won't help in this case. But, if you run it with -sin parameter, you can set the npp parameter as high as possible. If possible, please share with me the input files, so that I can have a look what's wrong. 
Please let me know if you have any further doubts or issues. 

Thanks, 
Akanksha

**Comment by nuriaserra** [comment]
Hello Akanksha,


That is strange...I attach the input file, and below you can see the head of a sample file. What I find more strange is that the mitochondrial DMRs are found and quite quickly, so I am not sure the problem is in the input files...but let's see.


nuria.serra@login1 [/lustre/scratch/users/nuria.serra/HOME/HOME_comparison1]> head SRR4999961_CG_matrix.tsv

chr1 109 + CG 3 3

chr1 110 - CG 2 2

chr1 115 + CG 4 4

chr1 116 - CG 2 2

chr1 161 + CG 6 7

chr1 310 + CG 9 17

chr1 500 + CG 18 29

chr1 501 - CG 1 1

chr1 511 + CG 25 33

chr1 512 - CG 1 1


Thank you for your help,


Núria


Nuria Serra
Intern

Gregor Mendel Institute of Molecular Plant Biology GmbH
Dr. Bohr-Gasse 3, 1030 Vienna, Austria
nuria.serra@gmi.oeaw.ac.at
http://www.gmi.oeaw.ac.at

[cid:gmisig_231_92997f80-ec0b-4736-9e1e-b20adcb9ca37.png]


________________________________

**Comment by Akanksha2511** [comment]
Closing this issue because of HPC related problem at the user end.

**Comment by Papareddy** [comment]
Hi Akanksha,

Just to be sure, is HOME compatable for single replicate  timeseries analysis (or pairwise) ?. I have HOME (>0.7)  working well for both timeseries or pairewise when i have multi replicates but never ending job run for single replicates as Nuria mentioned(with or without -sin paramether ). Do you think is there something do with single replicate experiments. And i also see double scalar error in these cases. We use the same HPC.

Cheers,
Ranj
